name: 'Setup node and npm dependencies'
inputs:
  node-version:
    description: 'Node version to use'
    required: true
    default: 18
  runner-os:
    description: 'Runner os to use'
    required: true
    default: 'ubuntu-latest'
runs:
  using: "composite"
  steps:
    - run: echo Setting up node and dependencies ${{ inputs.node-version }} and ${{ inputs.runner-os }}
      shell: bash
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: 'https://registry.npmjs.org'
    - name: Setup node cache
      uses: actions/cache@v3
      id: node-cache
      with:
        path: node_modules
        key: node-modules-${{ inputs.runner-os }}-node${{ inputs.node-version }}-${{ hashFiles('package-lock.json') }}
    - name: Install dependencies unless cached
      if: steps.node-cache.outputs.cache-hit != 'true'
      run: npm ci
      shell: bash
