
name: Build and deploy docs to github pages

on:
  push:
    branches:
      - master

jobs:
  build_docs_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: setup-node-and-npm
        uses: ./.github/actions/setup-node-and-npm-dependencies
      - name: Build docs
        run: npm run doc

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs